import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/files/Header";
import Footer from "@/files/Footer";
import MainButton from "@/files/MainButton";
import { CartProvider } from "@/files/context/CartContext";
import CartDrawer from "@/files/cart/CartDrawer";
import { AuthProvider } from "@/files/context/AurhContext";
import { SidebarProvider } from "@/files/context/SidebarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EN wholeseller platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black w-full flex-col flex min-h-screen relative text-black ${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32' width='7' height='7' fill='none' stroke='white'%3e%3cpath d='M0 .5H31.5V32'/%3e%3cpath d='M15 16v2M16 17h-2' stroke-width='2'/%3e%3c/svg%3e")`,
        }}
      >
        <div className="absolute inset-0 z-0 bg-[radial-gradient(ellipse_at_center,transparent_0%,black_100%)] pointer-events-none"></div>
        <SidebarProvider>
        <AuthProvider>
        <CartProvider>
        {children}
        </CartProvider>
        </AuthProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
