import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/files/admin/Sidebar";
import Header from "@/files/Header";
import Footer from "@/files/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EN wholeseller platform",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='min-h-screen max-sm:mt-8 w-full relative flex flex-col '>
      <header className="top-0 z-10 w-full fixed flex sm:hidden">
          <Header/>               
      </header>
      <div className="flex flex-row">

      <div className="relative z-10 flex max-sm:fixed h-screen">
        <Sidebar/>
      </div>
        {children}
      </div>
      <footer className="bg-black z-10 w-full bottom-0 max-sm:hidden">
          <Footer/>
        </footer>   
    </div>
  );
}
